<!DOCTYPE html>
<html>
<head>
    <title>Stock Valuation Report - {{ now()->format('Y-m-d') }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f5f5f5; font-weight: bold; }
        .header { text-align: center; margin-bottom: 20px; }
        .summary { background-color: #f0f9ff; border: 1px solid #bae6fd; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .text-right { text-align: right; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
        .low-stock { background-color: #fef2f2; }
        .out-of-stock { background-color: #fee2e2; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Stock Valuation Report</h1>
        <p><strong>Generated:</strong> {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="summary">
        <h2>Total Inventory Value: GHS {{ number_format($totalValue, 2) }}</h2>
        <p>Total Products: {{ $products->count() }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>SKU</th>
                <th>Product Name</th>
                <th class="text-right">Current Stock</th>
                <th class="text-right">Cost Price (GHS)</th>
                <th class="text-right">Stock Value (GHS)</th>
            </tr>
        </thead>
        <tbody>
            @forelse($products as $product)
            <tr class="{{ $product->current_stock == 0 ? 'out-of-stock' : ($product->current_stock <= ($product->reorder_level ?? 0) ? 'low-stock' : '') }}">
                <td>{{ $product->sku ?? 'N/A' }}</td>
                <td>{{ $product->name }}</td>
                <td class="text-right">{{ $product->current_stock }}</td>
                <td class="text-right">{{ number_format($product->cost_price, 2) }}</td>
                <td class="text-right">{{ number_format($product->stock_value, 2) }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="5" style="text-align: center;">No products found in inventory</td>
            </tr>
            @endforelse
        </tbody>
        @if($products->count() > 0)
        <tfoot class="total-row">
            <tr>
                <td colspan="3">TOTAL INVENTORY VALUE</td>
                <td class="text-right"></td>
                <td class="text-right">GHS {{ number_format($totalValue, 2) }}</td>
            </tr>
        </tfoot>
        @endif
    </table>

    <!-- Summary Statistics -->
    @if($products->count() > 0)
    <div style="margin-top: 30px;">
        <h3>Summary Statistics</h3>
        <table style="width: auto;">
            <tr>
                <td><strong>Total Products:</strong></td>
                <td>{{ $products->count() }}</td>
            </tr>
            <tr>
                <td><strong>Out of Stock:</strong></td>
                <td>{{ $products->where('current_stock', 0)->count() }}</td>
            </tr>
            <tr>
                <td><strong>Low Stock:</strong></td>
                <td>{{ $products->filter(fn($p) => $p->current_stock > 0 && $p->current_stock <= ($p->reorder_level ?? 0))->count() }}</td>
            </tr>
            <tr>
                <td><strong>In Stock:</strong></td>
                <td>{{ $products->filter(fn($p) => $p->current_stock > ($p->reorder_level ?? 0))->count() }}</td>
            </tr>
        </table>
    </div>
    @endif

    <div style="margin-top: 40px; font-size: 12px; color: #666; text-align: center;">
        <p>Report generated by Pharmacy POS System</p>
    </div>
</body>
</html>